### ISSUE TITLE
[URGENT] Spring not loading external configuration file

### ISSUE THREAD

**Issue by azhamn** [azhamn/COVID-19#27]
In the [FCMInitializer.java](../blob/master/src/main/java/lk/gov/govtech/covid19/firebase/FCMInitializer.java#L26) class we are loading the [FCM adminSDk](../blob/master/src/main/resources/credentials/covid-19-lk-dev-firebase-adminsdk.json) credentials file which is a .json file.

Since this file is located in the resources folder it loads fine when executing the jar, however in production environments where config files should be loaded externally, this file fails to load.

#### Recreation Steps
- build the jar using `mvn clean install` command
- copy the `application.yml to the target folder
- change the value of `firebase.configurations.path` in application.yml to `credentials/fcm.json`
- copy contents of [covid-19-lk-dev-firebase-adminsdk.json](../blob/master/src/main/resources/credentials/covid-19-lk-dev-firebase-adminsdk.json) to a new file created at `<targetDir>/credentials/fcm.json`
- run the jar using `java -jar covid19-1.0.0-SNAPSHOT.jar`

You should see the following error in your console:
```
2020-03-18 13:05:52.680 ERROR 52038 --- [           main] l.g.g.covid19.firebase.FCMInitializer    : class path resource [credentials/fcm.json] cannot be opened because it does not exist
```

The issue is for some reason spring is not loading the fcm.json file.

**Comment by azhamn** [comment]
need to confirm if this is the expected behaviour in spring for external files (non-configuration files). If not implementation has to be changed to:
```java
if (!externalFileExists()) {
    //load file from bundled resources
}
```

**Comment by SuKSW** [comment]
As per the suggestions tested, when the `application.yml` is edited to change `firebase.configurations.path` (referring to a file external to the jar), the path has to start with `file:` 

Example: when the credentials file is in the same folder as the jar
```
firebase: 
    configurations:
        path: file:filename.json
```
or
```
firebase: 
    configurations:
        path: file:<absolute path>
```
If the `application.yml` is not edited, then the credentials file included in the jar will be used.
